# Uncomment the next line to define a global platform for your project
platform :ios, '13.2'

target 'TactileMap' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TactileMap
  pod 'Hue'
  pod 'SideMenu'  

  target 'TactileMapTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TactileMapUITests' do
    # Pods for testing
  end

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.2'
    end
  end
end
